CourseMVC/Models/Course.cs
using DataAccess.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CourseMVC.Models
{
    public class CourseDetailViewModel
    {
        public Course Course { get; set; }
        public List<Student> Students { get; set; }
        public Student student { get; set; }

    }
}

CourseMVC/Controllers/CourseMVCController.cs
using BusinessLogic.BLL;
using CourseMVC.Models;
using DataAccess.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseMVC.Controllers
{
    public class CourseMVCController : Controller
    {

        public ActionResult GetCourses()
        {
            return View("GetCourses", CourseController.getCourses());
        }

        public ActionResult GetCourseDetail(int id)
        {
            var course = CourseController.getCourse(id);
            var students = StudentController.getStudentsOnACourse(id);
            var model = new CourseDetailViewModel
            {
                Course = course,
                Students = students
            };
            return View(model);
        }


        [HttpPost]
        public ActionResult UpdateCourse(CourseDetailViewModel model)
        {
            Course course = CourseController.getCourse(model.Course.Id);
            if (course != null)
            {
                course.Name = model.Course.Name;
                course.Room = model.Course.Room;

                CourseController.editCourse(course);

                return RedirectToAction("GetCourseDetail", new { id = course.Id });
            }

            return RedirectToAction("GetCourses");
        }
    }
}

CourseMVC/Controllers/StudentMVCController.cs
using BusinessLogic.BLL;
using CourseMVC.Models;
using DataAccess.Model;
using DataAccess.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseMVC.Controllers
{
    public class StudentMVCController : Controller
    {
        // GET: StudentMVC
        public ActionResult GetStudents()
        {
                return View(StudentController.getStudents());
            
        }


        public ActionResult CreateStudentView()
        {
            //StudentController.createStudent(name, age);
            return View("CreateStudentView");

        }

        [HttpGet]
        public ActionResult EditStudentView(int id)
        {
            return View(StudentController.getStudent(id));
        }


        [HttpPost]
        public ActionResult EditStudentView(Student student)
        {
            StudentController.editStudent(student);
            return RedirectToAction("GetStudents");
        }

        [HttpGet]
        public ActionResult DeleteStudentView(int id)
        {
            return View(StudentController.getStudent(id));
        }

        [HttpPost]
        public ActionResult DeleteStudentView(Student student)
        {
            StudentController.deleteStudent(student.Id);
            return RedirectToAction("GetStudents");
        }

        [HttpPost]
        public ActionResult CreateStudent(int age, string name)
        {
            if (age != 0 || name != null)
            {
                StudentController.createStudent(name, age);
                return RedirectToAction("GetStudents");
            }
            return RedirectToAction("CreateStudentView");
        }

     }
}

CourseMVC/Views/CourseMVC/GetCourseDetail.cshtml
@model CourseMVC.Models.CourseDetailViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit Course</title>
</head>
<body>
    <div>
        <h4>Edit Course</h4>
        <hr />
        @using (Html.BeginForm("UpdateCourse", "CourseMVC", FormMethod.Post))
        {
            @Html.HiddenFor(model => model.Course.Id)
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Course.Name)
                </dt>
                <dd>
                    @Html.TextBoxFor(model => model.Course.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Course.Room)
                </dt>
                <dd>
                    @Html.TextBoxFor(model => model.Course.Room)
                </dd>
            </dl>
            <p>
                <input type="submit" value="Save" /> |
                @Html.ActionLink("Back To Courses", "GetCourses", new { id = Model.Course.Id })
            </p>
        }
    </div>
    <hr />
    <div>
        <h4>Students attending the course</h4>
        <ul>
            @foreach (var student in Model.Students)
            {
                <li>@student.name</li>
            }
        </ul>
    </div>

</body>
</html>

CourseMVC/Views/CourseMVC/GetCourses.cshtml
@model IEnumerable<DataAccess.Model.Course>


@{
    Layout = null;
}



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetCourses</title>
    <style>
        table {
            border: 3px solid #ddd;
            border-collapse: collapse;
        }

        th, td {
            border: 3px solid #ddd;
            padding: 8px;
        }
    </style>
</head>
<body>
    <p>
        <h1>@Html.ActionLink("Create a new course", "Create")</h1>
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Name, "GetCourseDetail", new { id = item.Id })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Room)
                </td>
                <td>
                    @Html.ActionLink("Delete Course", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
    <p>
        <h2>@Html.ActionLink("See all students on campus", "GetStudents", "StudentMVC")</h2>
    </p>
</body>
</html>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CourseMVC/Views/StudentMVC/CreateStudentView.cshtml
@model DataAccess.Model.Student

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateStudent</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>



    @using (Html.BeginForm("CreateStudent", "StudentMVC", FormMethod.Post))
    {

        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Student</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create Student" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to students", "GetStudents")
    </div>
</body>
</html>

CourseMVC/Views/StudentMVC/DeleteStudentView.cshtml
@model DataAccess.Model.Student

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DeleteStudentView</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Student</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.age)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.age)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "GetStudents")
            </div>
        }
    </div>
</body>
</html>

CourseMVC/Views/StudentMVC/EditStudentView.cshtml
@model DataAccess.Model.Student

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditStudentView</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Student</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                    @Html.ActionLink("Delete", "Delete")
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "GetStudents")
    </div>
</body>
</html>

CourseMVC/Views/StudentMVC/GetStudents.cshtml
@model IEnumerable<DataAccess.Model.Student>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetStudents</title>
    <style>
        table {
            border: 3px solid #ddd;
            border-collapse: collapse;
        }

        th, td {
            border: 3px solid #ddd;
            padding: 8px;
        }
    </style>
</head>
<body>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.age)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            using (Html.BeginForm("EditStudentView", "StudentMVC", FormMethod.Post))
            {
                <tr>
                    <td>
                        @Html.TextBoxFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.TextBoxFor(modelItem => item.age)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "EditStudentView", new { id = item.Id })
                        @Html.ActionLink("Delete", "DeleteStudentView", new { id = item.Id })
                    </td>
                </tr>
            }
        }
    </table>
    @Html.ActionLink("Create a student", "CreateStudentView")
    @Html.ActionLink("Back to courses", "GetCourses", "CourseMVC")
</body>
</html>